### ISSUE TITLE
im sorry im just confused

### ISSUE THREAD

**Issue by FrankOcean11** [ibaaj/awesome-gif#5]
im looking for a C# and or C++ source that can let me give it a video and or convert a live video feed into a GIF file and store it for later parsing im using a C# prog made in Visual studio 2013/15 and i want to have this prog call the prog that you might suggest IF a condition is met

**Comment by ibaaj** [comment]
Video is just frames+audio. Extract frames of your video and use something like [ofxGifEncoder with OpenFrameworks](https://github.com/jesusgollonet/ofxGifEncoder).
